### PR TITLE
Add an animation to the BuddyCount component.

### PR DESCRIPTION
**Pull request by parithon**
This PR seeks to add a counter animation to the number of buddies fed.

CounterExample

### CODE REVIEW

**Comment by ElectricHavoc** [comment]
I also implemented something similar in my PR, however I removed any EF from the component and am using application state. I also am not using timer component.

Nice touch adding the gif to the PR.

I do like having animate as a property though!

**Comment by parithon** [comment]
I saw your PR #3, @ElectricHavoc, as soon as I added this one.

I believe the state should be used in the 'Page' and the needed attributes passed to this BuddyCount component as a parameter making the BuddyCount component more generic for any number represented on the site; thus we could use it elsewhere if we desire.

**Comment by parithon** [comment]
I am closing this PR in lieu of PR #3. I have another PR based on #3 that makes the BuddyCount a generic Counter component.

**Comment by ElectricHavoc** [comment]
> BuddyCount component as a parameter 

I was considering this also, as that's generally the pattern for library components, but since it's a smaller site and there is a state engine, there shouldn't be a need for the parent component to worry about it. There are ways to accommodate both, like the parameter could override and disable the state check, similar to enable / disable of animation. Both being UI only concerns that would pass that isolation. Forcing responsibility to the page has it's own consequences too, like if the control is used on several pages, they would all have to implement retrieval and property population. 

Both are solid possibilities, application state could also be passed as a parameter, but then it should be abstracted to an interface. That's the most 'enterprise' like solution but thought slightly overkill for the size of the app.

**Pull request closed without merging**
