### PR TITLE
Standard Blazor Enhancements - ⚡

### PR DESCRIPTION
**Pull request by ElectricHavoc**
- dotnet watch fix for css
- nullable enable
- buddy count refactor for app state
- enable user secrets
- startup common features
- healthchecks
- basic api for testing
- application state start
- blazor css fix

### CODE REVIEW

**Comment by ElectricHavoc** [comment]
To see the count animation, visit /count/707 while running in another window. Timing / spread TBD. Duplicate / bounds checking not implemented. For demo only. /count/# should be removed post testing / ef integration.

Mostly example for fun blazor demo.

**Comment by parithon** [comment]
Where do you get the initial buddy count from? Do we now need to enter a 'state' initialization where it grabs data from a data store, whatever type we choose?

**Comment by ElectricHavoc** [comment]
Count and initial db values should not be part of components, would be ideally bootstrapped with application and hydrated into application state. This allows a complete decoupling of state from db and UI. It also avoids any load caused by UI to impede on any db calls. Only external triggers (data additions or forced refresh) should be allowed to make those calls.

**Comment by parithon** [comment]
I've got a [branch](https://github.com/parithon/blazor-buddies/tree/init-state) ready to PR but it relies on your PR changes. Not sure the best way to submit the PR without the changes in this repo. I'll wait until @MichaelJolley commits this PR and then I'll create my PR.

**Review by michaeljolley — APPROVED** [review]

**Pull request merged**
